export const todoNotifications = {
  date: "Дата",
  codeTodo: "Шифр задачи",
  codeProject: "Шифр проекта",
  todo: "Задача",
  status: "Статус",
  responsible: "Ответственный",
  reassign: "Переназначить",
  priority: "Приоритет",
  comment: "Комментарий",
  planTime: "План время",
  factTime: "Факт время",
  start: "Начал",
  finish: "Завершил",
};
